# Generated by Django 3.2.9 on 2021-11-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('order_status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Stored', 'Stored'), ('Send', 'Send')], max_length=11)),
                ('store_account', models.CharField(max_length=3)),
            ],
        ),
    ]
